config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
  devise_for :users 
  root "splash#index"
  resources :users
  resources :groups, path: :categories  do
    resources :entities, path: :transactions
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :entity_groups

  validates :amount, numericality: { greater_than_or_equal_to: 0 }
  validates :name, presence: true, allow_blank: false, length: { maximum: 250 }
end

app/models/entity_group.rb
class EntityGroup < ApplicationRecord
  belongs_to :entity
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  has_one_attached :icon
  belongs_to :user
  has_many :entity_groups

  validates :name, presence: true, allow_blank: false, length: { maximum: 250 }
  validates :icon, presence: true, allow_blank: false
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :entities, foreign_key: 'author_id', dependent: :destroy
  has_many :groups, dependent: :destroy

  validates :name, presence: true, allow_blank: false, length: { maximum: 250 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email name password password_confirmation])
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :authenticate_user!

  def index
    @entities = Entity.includes(:entity_groups).where(entity_groups: { group_id: params[:group_id] },
                                                      author_id: current_user.id).order(created_at: :desc)
  end

  def new
    @groups = Group.where(user_id: current_user.id)
    @entity = Entity.new
    @entity_group = EntityGroup.new
  end

  def create
    @entity = Entity.new(entity_params)
    @entity.author_id = current_user.id
    @groups_array = entity_group_params

    if @groups_array.empty?
      redirect_to new_group_entity_path(params[:group_id]), alert: 'Please, add at least 1 category.'
    else
      render :new unless @entity.save

      @groups_array.each do |group|
        temp = EntityGroup.new(entity_id: @entity.id, group_id: group)
        render :new unless temp.save
      end
      redirect_to group_entities_path(@groups_array.first), notice: 'Transaction successfully created!'
    end
  end

  private

  def entity_params
    params.require(:entity).permit(:name, :amount)
  end

  def entity_group_params
    @array = params.require(:entity_group).permit(group_id: [])
    @array[:group_id].drop(1)
  end
end

app/controllers/group_controller.rb
class GroupController < ApplicationController
  def index
    @groups = Group.where(user_id: current_user.id)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id
    if @group.save
      redirect_to group_index_path, notice: 'New category added!'
    else
      render :new, notice: 'Please, complete all the required fields'
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = Group.where(user_id: current_user.id)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id
    if @group.save
      redirect_to groups_path, notice: 'New category added!'
    else
      render :new
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index
    redirect_to groups_path if current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    case [controller.controller_name, controller.action_name]
    when %w[groups new]
      'NEW CATEGORY'
    when %w[groups index]
      'CATEGORIES'
    when %w[entities new]
      'NEW TRANSACTION'
    when %w[entities index]
      'TRANSACTIONS'
    when %w[registrations new]
      'REGISTER'
    when %w[sessions new]
      'LOGIN'
    end
  end
end

app/helpers/entities_helper.rb
module EntitiesHelper
  def total_amount_per_transaction(entities)
    number_to_currency(entities.sum(&:amount))
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def total_amount_per_category(group)
    @entities = Entity.includes(:entity_groups).where(entity_groups: { group_id: group.id })
    number_to_currency(@entities.sum(&:amount))
  end
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/entities/index.html.erb
<div class='d-flex flex-column align-items-center'>
  <div class="d-flex vw-100 px-2 py-3 justify-content-between bg-light">
    <p class="m-0 text-secondary">
      Total ammount:
    </p>
    <strong>
      <%= total_amount_per_transaction(@entities) %>
    </strong>
  </div>
  <ul class="d-flex flex-column vw-100 p-0 mt-2">
    <% @entities.each do |entity| %>
      <li class="d-flex gap-2 m-2 p-2 bg-light text-dark border rounded align-items-center justify-content-between">
        <p class="m-0 text-secondary">
          <%= entity.name %>
        </p>
        <strong class="py-4">
          <%= number_to_currency(entity.amount) %>
        </strong>
      </li>
    <% end %>
  </ul>
  <div class="actions bg-second vw-100 p-2 fixed-bottom">
    <%= button_to 'Add a new transaction', new_group_entity_path, method: :get, class:'btn w-100 text-light border border-light' %>
  </div>
  <%= button_to groups_path, method: :get, class: 'btn fixed-top-left btn-lg text-light' do %>
    <i class="bi bi-arrow-left"></i>
  <% end %>
</div>

app/views/entities/new.html.erb
<div class='d-flex flex-column align-items-center mt-2'>
  <%= form_with model: @entity, url: group_entities_path, method: :post, local: true do |f| %>
    <div>
      <%= f.text_field :name, placeholder: "name", required: true, placeholder: 'Transaction name', class: 'form-control vw-100'  %>
    </div>
    <div>
      <%= f.number_field :amount, step: 0.01 , required: true, placeholder: 'Amount', class: 'form-control vw-100' %>
    </div>
    <div class='d-flex flex-column w-50 py-2 px-4 gap-1'>
      <%= fields_for @entity_group do |item| %>
        <%= item.collection_check_boxes :group_id, @groups, :id, :name, required: true do |c| %>
          <div>
            <%= c.check_box %>
            <%= c.label %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="actions fixed-top-right p-2">
      <%= f.submit "Save", class:'btn text-light' %>
    </div>
  <% end %>
  <%= button_to group_entities_path(params[:group_id]), method: :get, class: 'btn fixed-top-left btn-lg text-light' do %>
    <i class="bi bi-arrow-left"></i>
  <% end %>
</div>

app/views/group/new.html.erb
<main>
  <h1>New Category</h1>
  <%= form_with model: Group, url: group_index_path, method: :post, local: true do |f| %>
    <div>
      <%= f.label :name %>
      <%= f.text_field :name, placeholder: "name" %>
    </div>
    <div>
      <%= f.label :icon %>
      <%= f.file_field :icon %>
      </div>
    <div>
      <%= f.submit "Create" %>
    </div>
  <% end %>
</main>

app/views/groups/index.html.erb
<ul class="d-flex flex-column vw-100 p-0">
  <% @groups.each do |group| %>
    <%= link_to group_entities_path(group.id), method: :post, class: 'text-decoration-none' do %>
      <li class="d-flex gap-2 m-2 p-2 bg-light text-dark border rounded">
        <%= image_tag url_for(group.icon), class: 'img-thumbnail wxh-sm-20 wxh-md-15 w-25 h-25' %>
        <div class="d-flex align-items-center flex-fill justify-content-between">
          <p class="text-secondary m-0">
            <%= group.name %>
          </p>
          <strong>
            <%= total_amount_per_category(group) %>
          </strong>
        </div>
      </li>
    <% end %>
  <% end %>
</ul>
<div class="actions bg-second vw-100 p-2 fixed-bottom">
  <%= button_to 'Add a new category', new_group_path, method: :get, class:'btn w-100 text-light border border-light' %>
</div>

app/views/groups/new.html.erb
<div class='d-flex flex-column align-items-center mt-2'>
  <%= form_with model: @group, url: groups_path, method: :post, local: true do |f| %>
    <div>
      <%= f.text_field :name, placeholder: " Category name" , required: true, class: 'form-control vw-100' %>
    </div>
    <div class="form-control vw-100 d-flex flex-column flex-sm-row text-secondary">
      <%= f.label :icon, 'Add an image to the new category (mandatory).' %>
      <%= f.file_field :icon , required: true, class: 'btn' %>
      </div>
    <div class="actions fixed-top-right p-2">
      <%= f.submit "Save", class:'btn text-light' %>
    </div>
  <% end %>
  <%= button_to groups_path, method: :get, class: 'btn fixed-top-left btn-lg text-light' do %>
    <i class="bi bi-arrow-left"></i>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyAwesomeBudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "app", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
  </head>

  <body class='bg-gray'>
    <%= render 'layouts/partials/header' %>
    <%= render 'layouts/partials/sidebar' %>
    <main class='mt-5 pt-1'>
    <%= render 'layouts/partials/alerts' %>
      <%= yield %>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/partials/_alerts.html.erb
    <% if notice %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
      <p class="notice"><%= notice %></p>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <p class="alert"><%= alert %></p>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>

app/views/layouts/partials/_header.html.erb
<% unless controller.controller_name == 'splash' %>
  <header class='d-flex justify-content-center bg-main text-light pt-3 fixed-top'>
    <% if controller.controller_name == 'groups' && controller.action_name == 'index' %>
      <button class="btn fixed-top-left pt-3 btn-lg" type="button" data-bs-toggle="offcanvas" data-bs-target="#staticBackdrop" aria-controls="staticBackdrop">
        <i class="bi bi-list text-light"></i>
      </button>
    <% end %>
    <h1 class="h3">
      <%= page_title %>
    </h1>
  </header>
<% end %>

app/views/layouts/partials/_sidebar.html.erb
<aside class="offcanvas offcanvas-start bg-main" data-bs-backdrop="static" tabindex="-1" id="staticBackdrop" aria-labelledby="staticBackdropLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title font-billabong h1 text-light" id="staticBackdropLabel">My awesome budget app</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body text-center text-light pt-5">
    <div>
      <p>
        <%= current_user.name if current_user %>
      </p>
      <p>
        <%= current_user.email if current_user%>
      </p>
      <%= button_to 'logout', destroy_user_session_path, method: :delete, class: 'btn text-light text-decoration-underline' %>
    </div>
  </div>
</aside>

app/views/splash/index.html.erb
<div class='d-flex flex-column align-items-center vh-100 bg-light fixed-top'>
  <div class='d-flex align-items-center justify-content-center flex-fill'>
    <h1 class='font-billabong'>My awesome budget app</h1>
  </div>
  <div class='d-flex flex-column w-100 p-4 gap-2'>
    <%= button_to 'LOG IN', new_user_session_path, method: :get, class: 'btn btn-primary w-100' %>
    <%= button_to 'SIGN UP', new_user_registration_path, method: :get, class: 'btn btn-light w-100' %>
  </div>
</div>